# -*- coding: utf-8 -*-
"""Printer texts

CI_TEXT and CO_TEXT should have the same length.
"""

CI_TEXT_ES = "Ingreso: "
CO_TEXT_ES = "Salida:  "
HELMETS_TEXT_ES = "Cascos"
BASE_TEXT_ES = "Base"
HOURS_TEXT_ES = "Hora adicional"
HOURS_HELMETS_TEXT_ES = "Hora adicional - cascos"
CAR_ES = "CARRO"
PICKUP_ES = "CAMIONETA"
TRUCK_ES = "CAMION"
MOTORBIKE_ES = "MOTO"
BIKE_ES = "BICICLETA"
LOADING_CONFIG_ES = "ParqueaderoApp"
CONFIGURING_ES = "Configurando..."
CONFIG_READY_ES = "Impresora lista en"
ERROR_BAD_ID_ES = "Error: El Id del parqueadero no es valido."
ERROR_BAD_URL_ES = "Error: La url del servidor no es valida o no hay acceso a internet."
DATE_FORMAT_ES = "%d-%m-%Y %I:%M:%S %p"

CI_TEXT_EN = "Chk in:  "
CO_TEXT_EN = "Chk out: "
HELMETS_TEXT_EN = "Helmets"
BASE_TEXT_EN = "Base"
HOURS_TEXT_EN = "Additional hour"
HOURS_HELMETS_TEXT_EN = "Additional hour - helmets"
CAR_EN = "CAR"
PICKUP_EN = "PICKUP"
TRUCK_EN = "TRUCK"
MOTORBIKE_EN = "MOTORBIKE"
BIKE_EN = "BIKE"
LOADING_CONFIG_EN = "ParqueaderoApp"
CONFIGURING_EN = "Configuring..."
CONFIG_READY_EN = "Printer ready"
ERROR_BAD_ID_EN = "Error: The parking lot Id is not valid."
ERROR_BAD_URL_EN = "Error: The server url is not valid or there is not internet access."
DATE_FORMAT_EN = "%m-%d-%Y %I:%M:%S %p"
